### ISSUE TITLE
Control Channel

### ISSUE THREAD

**Issue by Vasolix** [wtfnotavailable/Discord-MusicBot#174]
## Is your feature request related to a problem? Please describe.

Doing this command creates a new channel this could disturb users

## Describe the ideal solution

Ask the user to select which channel they want to initialize it to. with a discord drop-down menu in the command

or another command ex: set-control-channel

**Comment by BioCla** [comment]
The concept is good, but unfortunately there are some limitations from Discord itself.
The control channel, in order to work, would need to be completely empty, which implies deleting all messages within the selected channel.
If you consider the medium usage of a channel it's gonna have a lot of messages, which the bot can't delete in an orderly time (due to discord limitations).
The obvious counter argument would be: "well, I'll just create an empty channel, and then have the bot set it up", to that I say: "It's what it's doing right now, but without the hassle of clicking on buttons and moving channels around".

If the problem you're having is about having the channel being created outside of a category, you can drag and drop the newly created channel into your preferred category and modify it however you like afterwards.
